config/routes.rb
Rails.application.routes.draw do
  
  resources :votes
  
  resources :comments
  
  resources :arguments
  
  resources :proposals do
    member do
      put :vote
    end
  end
  
  resources :decisions do
    resources :proposals
    
    member do
      put :publish
      put :vote
      get :result
    end
  end
  
  namespace :admin do
    resources :accounts
    
    resources :payments
  end
  
  resources :messages
  
  resources :memberships do
    member do
      put :accept
      get :activate
    end
  end
  
  resources :registrations do
    member do
      get :activate
    end
  end
  
  resources :pages
  
  resources :contentparts do
    member do
      put :up
      put :to_top
      put :down
      put :to_bottom
    end
  end
  
  resources :newsletters do
    member do
      put :ready
      post :test
    end
  end
  
  resources :articles do
    member do
      put :publish
    end
  end
  
  resources :events do
    resources :registrations
  end
  
  resources :contacts do
    member do
      get :activate
      get :unsubscribe
    end
    
    resources :messages
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login'=> :create
    delete 'logout' => :destroy
  end
  
  resources :accounts do
    collection do
      match :check, via: [ :get, :post ]
      match :request_password, via: [ :get, :post ]
    end
    member do
      match :reset_password, via: [ :get, :patch ]
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/search', to: 'application#search'
  get '/impressum', to: 'pages#impressum'
  get '/datenschutz', to: 'pages#datenschutz'
  
  # catch all route for database pages
  get '/*path', to: 'pages#show',
      constraints: lambda { |req|
          req.path.exclude? 'rails/active_storage' }
  
  root to: 'pages#root'
  
end

app/models/account.rb
class Account < ApplicationRecord
  include Tokenize
  after_initialize :fill_in_token
  after_destroy :ensure_an_admin_remains
  
  has_secure_password
  
  # --- RELATIONS ------------------------------
  
  belongs_to :contact
  accepts_nested_attributes_for :contact
  has_one_attached :picture
  
  has_many :articles, dependent: :nullify
  has_many :votes, dependent: :destroy
  
  # --- VALIDATIONS ----------------------------
  
  validates :token,
        presence: true,
        uniqueness: true
  validates :login, presence: true,
        uniqueness: true
  validates_presence_of :password, on: :create
  validates_confirmation_of :password, on: :create
  
  # --- SCOPES ---------------------------------
  
  scope :published, -> { all.reject { |a| !a.published? } }
  
  # --- INSTANCE METHODS -----------------------
  
  def to_param
    token
  end
  
  def name_text
    contact.name_text
  end
  def first_name
    contact.first_name
  end
  
  def published?
    is_team_member?
  end
  
  def accepted?
    status == 'accepted'
  end
  
  def is_admin?
    status == 'admin'
  end
  
  def is_editor?
    status == 'editor' or is_admin?
  end
  
  def is_team_member?
    status == 'team' or is_editor?
  end
  
  def is_confirmed?
    status = 'confirmed' or is_team_member?
  end
  
  def has_membership?
    contact and contact.membership
  end
  
  def membership
    contact.membership
  end
  
  def status_text
    case
      when ( status == 'confirmed' and has_membership? )
        'Mitglied'
      else
        status.capitalize
    end
  end
  
  def has_picture?
    picture.attached?
  end
  
  def picture_preview
    picture.variant( combine_options: { gravity: 'Center', resize: '800x800^', crop: '800x800+0+0', quality: '50' } )
  end
  
  # --- Voting ---------------------------------
  
  def can_vote_for?( in_proposal )
    in_proposal and in_proposal.votes.for_account( self ).all? { |v| v.status == 'new' }
  end
  
  # --- Mailings -------------------------------
  
  def send_password_reset
    if contact and contact.email.to_s.include?( '@' )
      logger.debug "> send_password_reset @ account -- id:#{id} email:#{contact.email}"
      
      self.reset_token = generate_token( 15 )
      self.reset_expires_at = Time.zone.now + 2.hours
      save!
      AccountsMailer.password_reset_mail( self ).deliver_later
    end
  end
  
  # --- Error Handling -------------------------
  
  class Error < StandardError
  end
  
  # --- CLASS METHODS --------------------------
  
  def self.t_status_select
    STATUS_OPTIONS.collect { |o| [ self.human_attribute_name( "status.#{o}" ), o ] }
  end
  
private
  
  def ensure_an_admin_remains
    if Account.count.zero?
      raise Error.new "Can't delete last user"
    end
  end
  
  # --- CONSTANTS ------------------------------
  
  STATUS_OPTIONS = [
    'new',
    'confirmed',
    'team',
    'editor',
    'admin'
  ]
  
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  include AccountHelper
  
  skip_before_action :require_team, only: [ :check, :request_password, :reset_password, :index, :show, :new, :edit, :create, :update ]
  before_action :set_account, only: [ :reset_password, :show, :edit, :update, :destroy ]
  
  # --- CUSTOM METHODS -------------------------
  
  # GET  /accounts/check
  # POST /accounts/check
  def check
    if request.post?
      @contact = Contact.find_by email: params[ :email ]
      
      if @contact.blank?
        redirect_to new_account_path( email: params[ :email ] ) and return
        
      elsif @contact.account.blank?
        token = @contact.generate_token
        @account = @contact.create_account(
            status: 'new',
            login: @contact.email,
            password: token,
            password_confirmation: token )
      end
      @contact.account.send_password_reset
      render :account_sent
    end
  end
  
  def request_password
    if request.post?
      @contact = Contact.find_by email: params[ :email ]
      logger.debug "-- @account:#{@contact.to_yaml}"
      
      unless @contact and @contact.account
        redirect_to login_path, notice: 'E-Mail konnte nicht identifiziert werden' and return
        
      else
        @contact.account.send_password_reset
      end
      
      render :password_sent
    end
  end
  
  def reset_password
    logger.debug "> reset_password @ account -- @account:#{@account.to_yaml} params[ :to ]:#{params[ :to ]}"
    
    unless request.patch?
      redirect_to root_path, alert: 'Nicht erlaubt!' and return if @account.blank? or params[ :to ].blank? or @account.reset_token != params[ :to ]
      redirect_to login_path, alert: 'Link ist abgelaufen!' and return if @account.reset_expires_at <= Time.zone.now - RESET_PASSWORD_LINK_VALID_SPAN
      
    else
      @account.status = 'confirmed' if @account.status == 'new'
      if @account.update( password: params[ :account ][ :password ], password_confirmation: params[ :account ][ :password_confirmation ], reset_token: nil )
        redirect_to login_path, notice: 'Password wurde neu gesetzt, bitte anmelden.'
        
      else
        render
      end
    end
  end
  
  # --- STANDARD CRUD METHODS ------------------
  
  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.published.shuffle
  end
  
  # GET /accounts/1
  # GET /accounts/1.json
  def show
    redirect_to accounts_path, alert: "Nicht freigegeben!" and return unless @account.published? or @account == current_account
  end
  
  # GET /accounts/new
  def new
    @account = Account.new( contact: Contact.new )
    unless params[ :email ].blank?
      @account.contact.email = params[ :email ]
      @account.login = params[ :email ]
    end
  end
  
  # GET /accounts/1/edit
  def edit
    redirect_to login_path,
            notice: 'Bitte anmelden!' and return unless h_account_editable?( @account )
  end
  
  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new( account_params )
    @account.status = 'new'
    @account.contact.status = 'new' if @account.contact
    
    respond_to do |format|
      if @account.save
        ContactsMailer.with( contact: @account.contact ).
            confirmation_mail.
            deliver_later
        
        set_current_account @account
        
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    redirect_to login_path,
            notice: 'Bitte anmelden!' and return unless h_editable?( @account )
    
    respond_to do |format|
      if @account.update( account_params )
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find_by token: params[ :id ]
    render_404 and return if @account.blank?
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require( :account ).permit( :login, :password, :password_confirmation, :displayname, :label, :description, :picture, :contact_attributes => [ :email, :first_name, :last_name, :is_member, :read_basics, :read_privacy, :wants_news ] )
  end
  
  # --- CONSTANTS ------------------------------
  
  RESET_PASSWORD_LINK_VALID_SPAN = 2.hours
  
end

app/controllers/admin/accounts_controller.rb
class Admin::AccountsController < ApplicationController
  include AccountHelper
  
  before_action :require_admin
  before_action :set_account, only: [ :show, :edit, :update, :destroy ]
  
  # --- CUSTOM METHODS -------------------------
  
  # --- STANDARD CRUD METHODS ------------------
  
  # GET /accounts
  # GET /accounts.json
  def index
    @status_selected = params[ :status ]
    if @status_selected.blank?
      @accounts = Account.order 'status, updated_at DESC'
    else
      @accounts = Account.where status: @status_selected
    end
  end
  
  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end
  
  # GET /accounts/new
  def new
    @account = Account.new( contact: Contact.new )
    unless params[ :email ].blank?
      @account.contact.email = params[ :email ]
      @account.login = params[ :email ]
    end
  end
  
  # GET /accounts/1/edit
  def edit
  end
  
  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new( account_params )
    @account.status = 'new'
    @account.contact.status = 'new' if @account.contact
    
    respond_to do |format|
      if @account.save
        ContactsMailer.with( contact: @account.contact ).
            confirmation_mail.
            deliver_later
        
        set_current_account @account
        
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update( account_params )
        format.html { redirect_to admin_account_path( @account ), notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_account
    @account = Account.find_by token: params[ :id ]
    render_404 and return if @account.blank?
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def account_params
    params.require( :account ).permit( :status, :login, :password, :password_confirmation, :displayname, :label, :description, :picture, :contact_attributes => [ :email, :first_name, :last_name, :is_member, :read_basics, :read_privacy, :wants_news ] )
  end
  
end

app/helpers/account_helper.rb
module AccountHelper
  
  def h_account_editable?( in_account )
    !current_account.blank? and
        in_account == current_account
  end
  
end

app/views/accounts/_form.html.haml
- cancel_button = nil unless defined? cancel_button
- initially_hidden = false unless defined? initially_hidden

= form_for @account, class: initially_hidden ? 'initially_hidden' : nil do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.account.one" ), count: @account.errors.count )
      %ul
        - @account.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.account.#{message.first}" )
        
      
    
  
  .field
    = f.label :login
    = f.text_field :login, placeholder: 'z.B. lisa.muster@organisator.org'
  
  .field
    = f.label :password
    = f.password_field :password
  
  .field
    = f.label :password_confirmation, 'Confirm please'
    = f.password_field :password_confirmation
  
  = render 'contacts/subform_account', form: f, contact: @account.contact
  
  .actions
    = f.submit class: 'button main'
  

app/views/accounts/_form_me.html.haml
- cancel_button = nil unless defined? cancel_button
- initially_hidden = false unless defined? initially_hidden

= form_for @account, class: initially_hidden ? 'initially_hidden' : nil do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.account.one" ), count: @account.errors.count )
      %ul
        - @account.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.account.#{message.first}" )
        
      
    
  
  .field
    = f.label :login
    = f.text_field :login, placeholder: 'z.B. lisa.muster@organisator.org'
    .help Am besten verwendest du hier deine E-Mail Adresse.
    
  
  .field.picture
    = f.label :picture
    = f.file_field :picture
  
  .field
    = f.label :displayname
    = f.text_field :displayname, placeholder: 'z.B. Spitzname'
  
  .field
    = f.label :label
    = f.text_field :label, placeholder: 'z.B. Redakteurin'
  
  .field
    = f.label :description
    = f.text_area :description, rows: 5,placeholder: 'z.B. eine kurze, überraschende Beschreibung deiner Person.'
  
  .actions
    = cancel_action
    = f.submit class: 'button main'
  

app/views/accounts/_preview.html.haml
= link_to account, class: 'preview account_preview', id: account.token do
  - if account.has_picture?
    = image_tag account.picture_preview, class: 'picture'
  - else
    = image_tag 'default_user.jpg', class: 'picture'
  
  - unless account.published?
    .status= account.status
  
  .next_arrow
    = image_tag 'sym/angle_right_s25.svg'
  
  .title= account.displayname
  .label= account.label
  .description= truncate account.description, length: 150
  

app/views/accounts/_show.html.haml
- if account == current_account
  %h4 Deine nicht öffentlichen Profil Daten
- else
  %h4 Nicht öffentliche Account Daten

%p
  Login:
  %strong= @account.login

.status_bar
  - if h_is_user?
    .badge{ title: 'hat einen Account' } A
  
  - if h_is_team_member?
    .badge{ title: 'ist Teil des Teams' } T
  - else
    .badge.inactive{ title: 'noch kein Teil des Teams' } T
  
  - if h_is_editor?
    .badge{ title: 'ist Website Editor' } E
  
  - if h_is_admin?
    .badge{ title: 'ist Website Admin' } S
  

app/views/accounts/account_sent.html.haml
- # --------------------------------------------
%p.form_explanation
  Vielen Dank für die Anforderung eines Accounts.
  %br
  Wir haben Dir einen Link zum Setzen Deines Password an die Adresse
  %br
  %strong= @contact.email
  gesendet.

%p
  Er sollte in den nächsten 15 Minuten ankommmen. Schaue bitte auch in Deinem Spam-Postfach nach.

app/views/accounts/check.html.haml
- h_title 'Neuen Account registrieren'
- h_description 'Hier kannst Du Dir einen neuen Account für unsere Website registrieren.'
- # --------------------------------------------

%p.form_explanation
  Um einen neuen Account anzulegen, gib bitte Deine E-Mail Adresse an. Wir
  %strong senden Dir dorthin einen Link
  zur Bestätigung.

= form_tag do
  .field
    = label_tag :email
    = text_field_tag :email, params[ :email ], placeholder: 'z.B. lisa.muster@organisator.org', autofocus: true
  
  .actions.clearfix
    = submit_tag 'Anlegen', |
          class: 'button'
    
  

app/views/accounts/edit.html.haml
- cancel_action = capture do
  = link_to 'Abbrechen', @account, class: 'button'

%h1 Profil ändern

= render 'form_me', cancel_action: cancel_action

app/views/accounts/index.html.haml
- h_title 'Unser Team'
- h_description( h_page_description_for 'accounts' )

%h1 Unser Team
%p
  Hier erfährst du mehr über die Menschen hinter
  %strong organisator.

- if h_is_editor?
  %p
    = link_to 'Neues Teammitglied...', new_account_path
  

%ul.accounts_list
  - @accounts.each do |account|
    %li= render 'preview', account: account
  

app/views/accounts/new.html.haml
%h1 Neuer Zugang

= render 'form'

app/views/accounts/password_sent.html.haml
- # --------------------------------------------
%p.form_explanation
  Wir haben Dir einen Link zum Neusetzen Deines Password an die Adresse
  %br
  %strong= @contact.email
  gesendet.

%p
  Er sollte in den nächsten 15 Minuten ankommmen. Schaue bitte auch in Deinem Spam-Postfach nach.

app/views/accounts/request_password.html.haml
- # --------------------------------------------
%p.form_explanation
  Um Ihr Password neu zu setzen, gib bitte Deine E-Mail Adresse an. Wir
  %strong senden Dir dorthin einen Link
  zum Neusetzen.

= form_tag do
  .field
    = label_tag :email
    = text_field_tag :email, params[ :email ], placeholder: 'z.B. lisa.muster@organisator.org'
  
  .actions.clearfix
    = submit_tag 'Anfordern', |
          class: 'button float-right'
    
  

app/views/accounts/reset_password.html.haml
- # --------------------------------------------
%p.form_explanation
  Gib bitte ein neues Password ein.

%p
  Es sollte mindestens 8 Zeichen lang sein und Ziffern, Gross- und Kleinbuchstaben enthalten.

= form_for @account, url: reset_password_account_path( @account ) do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= I18n.t( 'errors.template.header', model: I18n.t( "activerecord.models.account.one" ), count: @account.errors.count )
      %ul
        - @account.errors.messages.each do |message|
          %li= I18n.t 'errors.format', message: message.last.first, attribute: I18n.t( "activerecord.attributes.account.#{message.first}" )
        
      
    
  
  .field
    = f.label :password
    = f.password_field :password
  
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  
  .actions
    = f.submit 'Setzen', class: 'button main'
  

app/views/accounts/show.html.haml
- h_page_title "#{@account.contact.name_text} im Team Organisator"
- h_description truncate( strip_tags( @account.description ), length: 250 )
- if @account.has_picture?
  - h_image full_url_for( @account.picture_preview )

- # --------------------------------------------

.account_details
  - if @account.has_picture?
    = image_tag @account.picture_preview, class: 'picture'
  - else
    = image_tag 'default_user.jpg', class: 'picture'
  
  %h1= @account.displayname
  .label= @account.label
  - if h_is_admin?
    .status= @account.status
  
  .description= h_format @account.description
  
  - if h_account_editable? @account
    .internal_actions
      .block_label Nur für dich sichtbar
      .help_text
        Oben im weissen Bereich siehst du deine persönliche Profil Seite.
        - if h_is_team_member?
          Du bist Teil des Teams und damit ist diese Seite öffentlich sichtbar.
        - else
          Wenn das Team dich akzeptiert und freigeschaltet hat, ist sie öffentlich sichtbar. Kontaktiere deine Ansprechperson, wenn du ins Team möchtest.
        
      
      .action_buttons
        = button_to 'Abmelden', logout_path, method: :delete, class: 'danger'
        
      
      %hr
      = render 'show', account: @account
      %p
        = link_to 'Bearbeiten', edit_account_path( @account ), class: 'button'
      
      %hr
      = render 'contacts/show', contact: @account.contact
      %p
        = link_to 'Bearbeiten', edit_contact_path( @account.contact ), class: 'button'
      
      %hr
      - unless @account.contact.membership
        %h4 Weitermachen?
        - if @account.is_team_member?
          %p
            Im Augenblick bist du Team-Mitglied.
          
        - else
          %p
            Im Augenblick bist du Interessent:in.
          
        
        %p
          Wenn du dich noch mehr einbringen möchtest, kannst du auch eine Mitgliedschaft bei Organisation beantragen.
          %br
          = link_to 'zum Mitgliedsantrag', new_membership_path
        
      - else
        %h4 Mitgliedschaft
        %p
          Du bist bei uns Mitglied und das freut uns. Danke!
        
      
    
  